description: >
  This executor uses our the SOOS DAST Docker Image to perform the scan.
docker:
  - image: 'soosio/dast:<<parameters.tag>>'
parameters:
  tag:
    default: "latest"
    type: string
    description: >
      Pick a specific version of soosio/dast:
      https://hub.docker.com/r/soosio/dast/tags
